#! /bin/bash
if [ -z "$1" ]
 then
   echo "Local, Public, of Both"
   exit
fi
# LOCAL
if [ $1 = "l" ] || [ $1 = "L" ] || [ $1 = "local" ] || [ $1 = "Local" ]
  then
   echo "*** MAKE SURE YOU ARE CONNECTED ***"
   echo " First, connect to SecurityServer;"
   echo "    LOCAL: SecurityServer"
   echo "Press [Enter] if ready . . ."
   read input
   echo "Pushing Files SecurityServer"
   yes | cp -r ./* /home/jer/SecurityServer/home/jer/Node_Local/node.askjer.com/public/
   echo " . . . Push to SecurityServer complete"
   echo ""
      exit
  else
   # PUBLIC
   if [ $1 = "p" ] || [ $1 = "P" ] || [ $1 = "public" ] || [ $1 = "Public" ]
     then
      echo "*** MAKE SURE YOU ARE CONNECTED ***"
      echo " First, connect to the public server;"
      echo "   PUBLIC: node.askjer.com"
      echo "Press [Enter] if ready . . ."
      read input
      echo "Pushing Files to node.askjer.com"
      yes | cp -r ./* /home/jer/Node_VPS/node.askjer.com/public/
      echo " . . . Push to node.askjer.com complete"
      echo ""
         exit
     else
      # BOTH SERVERS
      if [ $1 = "b" ] || [ $1 = "B" ] || [ $1 = "both" ]
        then
         echo "*** MAKE SURE YOU ARE CONNECTED ***"
         echo " First, connect to both servers;"
         echo "   PUBLIC: node.askjer.com"
         echo "    LOCAL: SecurityServer"
         echo "Press [Enter] if ready . . ."
         read input
         echo "Pushing Files to node.askjer.com"
         yes | cp -r ./* /home/jer/Node_VPS/node.askjer.com/public/
         echo " . . . Push to node.askjer.com complete"
         echo ""
         echo "Pushing Files SecurityServer"
         yes | cp -r ./* /home/jer/SecurityServer/home/jer/Node_Local/node.askjer.com/public/
         echo " . . . Push to SecurityServer complete"
         echo ""
            exit
        else
         echo "Local, Public, of Both"
      fi
   fi
fi
